### PR TITLE
Typed stack

### PR DESCRIPTION
**Pull request by Jakobeha**
current version of typed stack, fixed some bugs

### CODE REVIEW

**Comment by o-** [comment]
Hey, awesome, its great that we have a version that passes tests and also works well on mandelbrot (+26%). I gave this a spin with [my benchmark scripts](https://github.com/o-/rir-rebench-scripts). Unfortunately with the overall picture it's not quite there yet. So I'll let you play some more with the details I guess. The benchmark script is really handy to get a quick overview locally.

Also, if this is resolved, if you can clean up the history and manage to have all the whitespace changes and clang formating in one separate commit, that would greatly help with the reviewing.

```
# ./diff.rb typedStack.data master.data 
Bounce                                   0.92	±2  	(0.95)    	wu: 97	vs. 90
Mandelbrot                               1.26	±22 	(1.02)    	wu: 2049	vs. 2584
Storage                                  0.82	±5  	(0.83)    	wu: 167	vs. 137
binarytrees                              0.86	±3  	(0.87)    	wu: 302	vs. 259
binarytrees_2                            0.85	±2  	(0.86)    	wu: 293	vs. 250
binarytrees_naive                        0.88	±3  	(0.89)    	wu: 286	vs. 251
fannkuchredux                            0.9	±1  	(1.0)    	wu: 24	vs. 22
fannkuchredux_naive                      0.79	±1  	(0.97)    	wu: 23	vs. 18
fasta                                    0.8	±14 	(0.84)    	wu: 244	vs. 195
fasta_2                                  0.78	±19 	(0.91)    	wu: 215	vs. 168
fasta_3                                  0.87	±5  	(0.91)    	wu: 190	vs. 166
fasta_naive                              0.76	±2  	(0.87)    	wu: 123	vs. 93
fasta_naive_2                            0.74	±1  	(0.96)    	wu: 33	vs. 24
fastaredux                               0.81	±6  	(0.96)    	wu: 96	vs. 78
fastaredux_naive                         0.74	±5  	(0.91)    	wu: 117	vs. 86
knucleotide                              0.86	±0  	(0.97)    	wu: 27	vs. 23
knucleotide_brute                        0.92	±0  	(1.01)    	wu: 15	vs. 14
knucleotide_brute_2                      0.88	±0  	(0.99)    	wu: 14	vs. 13
knucleotide_brute_3                      0.93	±1  	(1.01)    	wu: 19	vs. 18
mandelbrot_ascii                         1.05	±15 	(1.08)    	wu: 250	vs. 263
mandelbrot_naive_ascii                   0.88	±2  	(0.92)    	wu: 99	vs. 87
mandelbrot_noout                         0.98	±1  	(0.99)    	wu: 223	vs. 219
mandelbrot_noout_naive                   1.02	±8  	(1.02)    	wu: 254	vs. 259
nbody                                    0.85	±0  	(0.94)    	wu: 43	vs. 37
nbody_2                                  0.9	±5  	(0.96)    	wu: 47	vs. 42
nbody_3                                  0.94	±5  	(0.99)    	wu: 46	vs. 43
nbody_naive                              0.94	±2  	(0.98)    	wu: 158	vs. 149
nbody_naive_2                            0.88	±0  	(0.98)    	wu: 23	vs. 20
pidigits                                 1.08	±4  	(1.0)    	wu: 186	vs. 201
regexdna                                 1.02	±0  	(1.01)    	wu: 30	vs. 31
reversecomplement                        1.0	±2  	(1.0)    	wu: 35	vs. 35
reversecomplement_2                      1.0	±9  	(1.04)    	wu: 168	vs. 167
reversecomplement_naive                  0.85	±16 	(0.86)    	wu: 511	vs. 432
spectralnorm                             0.73	±6  	(0.82)    	wu: 117	vs. 85
spectralnorm_alt                         1.01	±2  	(1.0)    	wu: 30	vs. 30
spectralnorm_alt_2                       1.01	±0  	(1.01)    	wu: 33	vs. 34
spectralnorm_alt_3                       0.89	±3  	(0.92)    	wu: 286	vs. 255
spectralnorm_alt_4                       1.1	±2  	(1.09)    	wu: 84	vs. 93
spectralnorm_math                        1.01	±7  	(1.01)    	wu: 208	vs. 211
spectralnorm_naive                       0.74	±0  	(0.88)    	wu: 60	vs. 45
                                         0.91		(0.96)
```

**Comment by charig** [comment]
@Jakobeha You asked for my review here. But what do you want me to review? I think this is very similar to my typed-stack2 branch? Is there a way of just looking at the differences?

**Comment by Jakobeha** [comment]
@o- I can clean up the commit history. I'm not sure how to optimize this further, but one thing I can try is to make the typed stack optional, so we can profile repeated functions running with/without, and decide whether individual functions should use the typed stack or not. We initially alternate between typed stack and regular, keeping a running average time of both, and then shift towards running the faster version more. Ideally, this would keep the speedup in mandelbrot while not slowing down the other functions too much.

@charig I just wanted to know if there was anything new you added, like storing cache values on the stack, that you'd want to see in this branch. I know you were also working on this, so if you have any suggestions or things you found

**Comment by charig** [comment]
I have an implementation for caching values on the stack yes. And there is some interleaving. But I guess a raw typed stack implementation first is the best approach. For the numbers, I think we are finally pretty near. It would be good to look why we manage such a speedup in mandelbrot but nothing similar in other benchmarks. That may give us a hint. Then, last time I checked there were still lot of extra conversions that we may be able to avoid. I do not remember now exactly those but, for instance, I recall having the impression that `gnu-r` use SEXPs for all the builtins while we are checking for unboxed values.

**Comment by Jakobeha** [comment]
@o- I tried to fix some white-space changes, but most of the changes aren't just whitespace but also small changes to deal with stack objects instead of SEXPs, e.g. `R_bcstack_t x = ...` instead of `SEXP x = ...`

**Comment by Jakobeha** [comment]
I replaced the builtins code so it uses SEXPs, and it looks like it didn't cause much difference. Here are the benchmarks (ran on `prl5`):

```
./diff.rb ts2.data master.data
Bounce                                   0.91	±1  	(0.95)    	wu: 95	vs. 87
Mandelbrot                               1.17	±50 	(1.05)    	wu: 2108	vs. 2477
Storage                                  0.82	±7  	(0.79)    	wu: 165	vs. 136
binarytrees                              0.85	±4  	(0.85)    	wu: 312	vs. 265
binarytrees_2                            0.9	±17 	(0.86)    	wu: 294	vs. 265
binarytrees_naive                        0.85	±16 	(0.83)    	wu: 302	vs. 256
fannkuchredux                            0.96	±0  	(1.0)    	wu: 24	vs. 23
fannkuchredux_naive                      0.82	±1  	(0.99)    	wu: 23	vs. 19
fasta                                    0.99	±50 	(0.93)    	wu: 210	vs. 208
fasta_2                                  1.02	±35 	(0.97)    	wu: 177	vs. 181
fasta_3                                  0.89	±13 	(0.84)    	wu: 193	vs. 172
fasta_naive                              0.78	±1  	(0.77)    	wu: 119	vs. 93
fasta_naive_2                            0.77	±1  	(0.79)    	wu: 33	vs. 25
fastaredux                               0.72	±0  	(0.77)    	wu: 102	vs. 73
fastaredux_naive                         0.87	±15 	(0.8)    	wu: 116	vs. 102
knucleotide                              0.87	±0  	(0.9)    	wu: 27	vs. 23
knucleotide_brute                        0.91	±1  	(0.84)    	wu: 16	vs. 14
knucleotide_brute_2                      0.89	±0  	(0.84)    	wu: 15	vs. 14
knucleotide_brute_3                      0.94	±1  	(0.83)    	wu: 20	vs. 19
mandelbrot_ascii                         0.95	±29 	(0.88)    	wu: 272	vs. 258
mandelbrot_naive_ascii                   0.84	±0  	(0.92)    	wu: 106	vs. 88
mandelbrot_noout                         0.93	±1  	(0.92)    	wu: 241	vs. 225
mandelbrot_noout_naive                   1.08	±29 	(1.05)    	wu: 292	vs. 314
nbody                                    0.88	±1  	(0.96)    	wu: 44	vs. 38
nbody_2                                  0.88	±1  	(0.86)    	wu: 46	vs. 40
nbody_3                                  0.93	±0  	(0.89)    	wu: 45	vs. 41
nbody_naive                              0.9	±2  	(0.96)    	wu: 164	vs. 147
nbody_naive_2                            0.9	±0  	(0.9)    	wu: 24	vs. 21
pidigits                                 0.98	±3  	(0.87)    	wu: 189	vs. 185
regexdna                                 1.0	±0  	(0.97)    	wu: 30	vs. 30
reversecomplement                        0.94	±3  	(0.96)    	wu: 38	vs. 36
reversecomplement_2                      0.96	±10 	(0.99)    	wu: 176	vs. 168
reversecomplement_naive                  0.86	±9  	(0.83)    	wu: 496	vs. 428
spectralnorm                             0.79	±1  	(0.79)    	wu: 115	vs. 91
spectralnorm_alt                         1.0	±2  	(1.0)    	wu: 32	vs. 32
spectralnorm_alt_2                       1.0	±0  	(0.99)    	wu: 36	vs. 36
spectralnorm_alt_3                       0.89	±3  	(0.86)    	wu: 283	vs. 253
spectralnorm_alt_4                       1.11	±4  	(1.02)    	wu: 89	vs. 98
spectralnorm_math                        1.0	±4  	(1.0)    	wu: 209	vs. 209
spectralnorm_naive                       0.9	±0  	(0.82)    	wu: 54	vs. 49
                                         0.92		(0.9)
```

**Pull request closed without merging**
