### PR TITLE
Dirty fix for #488

### PR DESCRIPTION
**Pull request by Jakobeha**

### CODE REVIEW

**Review by charig — APPROVED** [review]
I was thinking 2 things:
* if `hangCounter++;` is inside an assert that may help in terms of documentation for the future (it is a debugging check)
* Isn't 1000000 to high?

**Comment by Jakobeha** [comment]
I tested on my local machine and 1000000 triggered the error when there was still vm left.

**Comment by mhyee** [comment]
How long did it take to trigger the error? One reason for a smaller limit is to catch the error earlier.

**Comment by Jakobeha** [comment]
Not more than about 5secs, I dropped it to 100000

**Comment by o-** [comment]
static variables are shared between all invocations. this method is used for compiling promises, while compiling the actual function. thus the counter is always reset when you compile a promise. i verified that it fails to catch the original error. please test your changes. also I don't like the approach, something like a hang counter should be really last resort, after we properly analyzed the problem and convinced ourselves that an actual solution is infeasible.

**Pull request merged**
