### PR TITLE
bump binding cache size

### PR DESCRIPTION
**Pull request by JanJecmen**

### CODE REVIEW

**Comment by JanJecmen** [comment]
Is there a way to restart the gitlab jobs?

**Comment by o-** [comment]
why are you proposing this?

**Comment by JanJecmen** [comment]
We talked about it with Jan and Guido and in gnur they have a cache that's 256 elements big..
I measured a couple different sizes and this gave the best results
```
binarytrees                              0.96
binarytrees_2                            1.0
fannkuchredux                            1.03
fannkuchredux_naive                      0.99
fasta                                    1.44
fastaredux_naive                         0.98
knucleotide                              1.01
Mandelbrot                               1.01
mandelbrot_noout_naive                   0.98
nbody                                    1.01
nbody_naive                              0.99
pidigits                                 1.0
regexdna                                 1.01                                                                                                          
reversecomplement                        1.01                                                                                                          
spectralnorm                             0.98                                                                                                          
spectralnorm_naive                       1.01                                                                                                          
1.03                                                      
```

**Comment by o-** [comment]
@JanJecmen ok, thanks.

**Comment by o-** [comment]
@JanJecmen http://rflies.rir.o1o.ch/changes/?tre=10&rev=df222003a9e892ace78e2b2dc10d3568a54993a0&exe=3&env=1

should we revert?

**Comment by JanJecmen** [comment]
oh wow, ok
yeah, let's revert

**Pull request merged**
