### PR TITLE
[wip] GraphViz

### PR DESCRIPTION
**Pull request by Jakobeha**
This adds GraphViz output to PIR ([#324]). Enable either by passing `PIR_DEBUG_STYLE=GraphViz`, or calling `pir.compile(fun, debugStyle=GraphViz)`.

Currently not much more than @o-'s example. Only `pir::Code`'s are changed. The GraphViz is in raw DOT, so it's not ideal (see the example).

I implemented this by adding a custom class, `PrintStream`, and replacing uses of `std::ostream` with it. In the future, we can add a lot more output styles, and customize almost anything that gets printed. 

After this, I plan to add an alternate GraphViz output which only prints the BB's numbers (as suggested), and if there's a program/library for it, outputs for ASCII art GraphViz.

Sample output.

<pre><font color="#295FCC"><b>╞═══════════════════════════════╡  </b></font>Compiling f<font color="#295FCC"><b>  ╞══════════════════════════════╡</b></font>

<font color="#FF8787"><b>┌──────────────────────────────────────────────────────────────────────────────┐</b></font>
<font color="#FF8787"><b>│ f[0x55f8a48730e0]                                                            │</b></font>
<font color="#FF8787"><b>│ Assumptions: CorrOrd, !TMany                                                 │</b></font>
<font color="#FF8787"><b>│ Properties:  Eager, ForceOrd: 0                                              │</b></font>
<font color="#FF8787"><b>├────── PIR Version After Optimizations</b></font>
f[0x55f8a48730e0]
digraph {
  BB0 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
val?^   %0.0  = LdArg            0\l\
env     e0.1  = MkEnv            x=%0.0, parent=<font color="#DED82C"><b>&lt;environment: R_GlobalEnv&gt;</b></font>\l\
val?    %0.2  = Force!           %0.0, <font color="#CC58CC"><b>e0.1</b></font>\l\
real$&apos;  %0.3  = LdConst          [1] 1 \l\
cp      %0.4  = Checkpoint       \l\
&quot;];
  BB0 -&gt; BB2;
  BB0 -&gt; BB1 [color=red];

  BB2 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
t       %2.0  = IsObject         %0.2\l\
void            AssumeNot        %2.0, %0.4\l\
lgl&apos;    %2.2  = Lt               %0.2, %0.3, elided\l\
t       %2.3  = AsTest           %2.2\l\
void            Branch           %2.3\l\
&quot;];
  BB2 -&gt; BB4 [color=green];
  BB2 -&gt; BB3 [color=red];

  BB1 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
fs      %1.0  = FrameState       1+45: [%0.2, %0.3], env=<font color="#DED82C"><b>e0.1</b></font>\l\
void            Deopt            %1.0\l\
&quot;];

  BB4 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
&quot;];
BB4 -&gt; BB5;

  BB3 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
nil&apos;    %3.0  = LdConst          NULL \l\
void            Invisible        \l\
&quot;];
BB3 -&gt; BB12;

  BB5 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
val?^   %5.0  = LdVar            x, <font color="#DED82C"><b>e0.1</b></font>\l\
val?    %5.1  = Force            %5.0, <font color="#CC58CC"><b>e0.1</b></font>\l\
real$&apos;  %5.2  = LdConst          [1] 4 \l\
cp      %5.3  = Checkpoint       \l\
&quot;];
  BB5 -&gt; BB7;
  BB5 -&gt; BB6 [color=red];

  BB12 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
nil&apos;    %12.0 = Phi              %3.0:BB3, %8.0:BB8\l\
void            Return           %12.0\l\
&quot;];

  BB7 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
t       %7.0  = IsObject         %5.1\l\
void            AssumeNot        %7.0, %5.3\l\
lgl&apos;    %7.2  = Lt               %5.1, %5.2, elided\l\
t       %7.3  = AsTest           %7.2\l\
void            Branch           %7.3\l\
&quot;];
  BB7 -&gt; BB9 [color=green];
  BB7 -&gt; BB8 [color=red];

  BB6 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
fs      %6.0  = FrameState       1+108: [%5.1, %5.2], env=<font color="#DED82C"><b>e0.1</b></font>\l\
void            Deopt            %6.0\l\
&quot;];

  BB9 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
val?^   %9.0  = LdVar            x, <font color="#DED82C"><b>e0.1</b></font>\l\
val?    %9.1  = Force            %9.0, <font color="#CC58CC"><b>e0.1</b></font>\l\
str$&apos;   %9.2  = LdConst          [1] \&quot;foo\&quot; \l\
cp      %9.3  = Checkpoint       \l\
&quot;];
  BB9 -&gt; BB11;
  BB9 -&gt; BB10 [color=red];

  BB8 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
nil&apos;    %8.0  = LdConst          NULL \l\
void            Invisible        \l\
&quot;];
BB8 -&gt; BB12;

  BB11 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
t       %11.0 = IsObject         %9.1\l\
void            AssumeNot        %11.0, %9.3\l\
val?&apos;   %11.2 = Add              %9.1, %9.2, elided\l\
void            StVar            x, %11.2, <font color="#FF8787"><b>e0.1</b></font>\l\
void            Invisible        \l\
&quot;];
BB11 -&gt; BB5;

  BB10 [shape=&quot;box&quot;, fontname=&quot;monospace&quot;, label=&quot;\
fs      %10.0 = FrameState       1+160: [%9.1, %9.2], env=<font color="#DED82C"><b>e0.1</b></font>\l\
void            Deopt            %10.0\l\
&quot;];

}

<font color="#FF8787"><b>│ f[0x55f8a48730e0]                                                            │</b></font>
<font color="#FF8787"><b>└──────────────────────────────────────────────────────────────────────────────┘</b></font></pre>

### CODE REVIEW

**Comment by o-** [comment]
> I implemented this by adding a custom class, `PrintStream`, and replacing uses of `std::ostream` with it. In the future, we can add a lot more output styles, and customize almost anything that gets printed.

I am not happy about this solution. Can you elaborate why such a heavyweight approach is necessary?

I am very concerned that this will make it basically impossible to run print from the debugger. And cause many more problems when we try to use the print functionality in other contexts. Replacing cout is not convenient. I explicitly refrained from it, when I added the colors (that's why there is a `isTty` boolean flag to all print functions).

I find it is the wrong abstraction level to approach that issue. I would have just added a `printGraph` function on functions and bbs. The instructions themselves should stay unchanged.

**Comment by o-** [comment]
@Jakobeha hey, I still think that this would be quite a useful addition. do you think you could implement the simpler version, we talked about, that does not require changing the type the stream arguments?

**Comment by Jakobeha** [comment]
No problem. I also added the ability to just print the BBs, although it looks like you might've already done this locally

**Comment by o-** [comment]
@Jakobeha awesome, thanks!

I would like to merge, but you accidentially commited a changed git submoduel for gnur. you need to ensure  that `external/custom-r` is unchanged with regards to master.

**Comment by Jakobeha** [comment]
Should be fixed now

**Comment by charig** [comment]
It would be great if the PR also updates the documentation on how to use this new debugging option

**Pull request merged**
