### PR TITLE
Omit deopt branch

### PR DESCRIPTION
**Pull request by o-**

### CODE REVIEW

**Comment by o-** [comment]
just an additional printing flag, tbr

**Comment by mhyee** [comment]
Please update https://github.com/reactorlabs/rir/blob/master/documentation/debugging.md

One comment: in gdb, when I want to print a function, I have to go `p c->printStandard(std::cerr, true)`. I can't omit the flag. So now I guess I have to write `p c->printStandard(std::cerr, true, true)`?

**Comment by o-** [comment]
> One comment: in gdb, when I want to print a function

yeah, don't have a better solution. because default args (or proxy functions) are usually optimized away and not available in gdb either. that's why i didn't bother....

**Comment by o-** [comment]
you can do `1,1` instead of `true,true` ;)

**Pull request merged**
