### PR TITLE
Fix typo in rir.eval

### PR DESCRIPTION
**Pull request by JanJecmen**
The default argument for env should be globalenv() (all lowercase).

### CODE REVIEW

**Comment by o-** [comment]
that's all good of course! I would not mind if you merge such simple things with the comment "to be reviewed", then we can still retroactively comment...

**Comment by JanJecmen** [comment]
I don't have write access so I couldn't merge, sorry. I know it's just one letter change..

**Comment by o-** [comment]
ah sorry that was not the intention. Nobody should be able to push directly but everybody should be allowed to merge a PR where the checks are green. Can you try again. Changed some settings.

**Comment by JanJecmen** [comment]
Works fine now, thanks

**Pull request merged**
