### PR TITLE
we can't use exceptions due to longjmp, might as well disable them

### PR DESCRIPTION
**Pull request by o-**

### CODE REVIEW

**Comment by mhyee** [comment]
What version of gcc do you have? On the server, I'm using 7.3.0, and after I remove the "ignore strict overflow" pragma, I don't see any errors.

With gcc 8.2.0, I get a different warning:

```
rir/src/ir/BC_inc.h: In static member function ‘static rir::BC::ImmediateArguments rir::BC::decodeImmediateArguments(rir::Opcode, rir::Opcode*)’:
rir/src/ir/BC_inc.h:616:47: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘struct rir::BC::StaticCallFixedArgs’ from an array of ‘enum class rir::Opcode’ [-Wclass-memaccess]
                    sizeof(StaticCallFixedArgs));
```

**Comment by o-** [comment]
@mhyee also 7.3.0, but only in release build. and yes I have also seen the 8.2.0 warning, which is legit, but we are taking precautions (so we'll have to silence that one too).

**Comment by mhyee** [comment]
Ah, I thought running `cmake -GNinja . ` would set release mode by default, but I had to explicitly write `-DCMAKE_BUILD_TYPE=release`.

Once you silence the mem access warning, I think this PR is good to merge.

**Review by mhyee — APPROVED** [review]

**Comment by mhyee** [comment]
For what it's worth, I don't see either warning with clang 7.0.1.

**Comment by mhyee** [comment]
Actually, I just realized that `.ycm_extra_conf.py` is missing `-fno-rtti -fno-exceptions`.

**Comment by o-** [comment]
> Actually, I just realized that .ycm_extra_conf.py is missing -fno-rtti -fno-exceptions.

good catch!

**Comment by o-** [comment]
> Once you silence the mem access warning, I think this PR is good to merge.

this warning is actually not introduced by this commit, but already older. And now I cannot reproduce it anymore on 8.2.1 so maybe it was fixed on gcc's end.

UPDATE: ok, now i was able to repro and silenced it.

**Comment by o-** [comment]
I hate those stupid warning flags across compilers. Travis says:

> /home/travis/build/reactorlabs/rir/rir/src/ir/BC_inc.h:582:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
> #pragma GCC diagnostic ignored "-Wclass-memaccess"
>                                ^~~~~~~~~~~~~~~~~~~

I am just gonna revert this part and stick to the version that works on travis and apparently on most of our machines.

**Comment by mhyee** [comment]
Sorry, but I lost track: what's the current status here? Will you be opening (or re-opening) a PR for (some) of these changes, or is this dead?

**Comment by mhyee** [comment]
Oh, I see it already got merged in 811a1f8f6cc98ac9c6783a6160057405687d8f7d.

**Pull request closed without merging**
