### PR TITLE
Enable super subassign

### PR DESCRIPTION
**Pull request by JanJecmen**
@o- There was a comment about an issue with super assign and double bracket.. Do you remember how that issue manifested?

### CODE REVIEW

**Comment by JanJecmen** [comment]
I guess gitlab found it ;D

**Comment by JanJecmen** [comment]
One of those I cannot reproduce :(

EDIT:
not sure about this one.. if I go to external/custom-r/tests and repeatedly run `make test-Random` I get this (very low probability) in the log:
```
> dkwtest("gamma",shape =  0.2)
gamma(shape = 0.2) FAILED
Error in dkwtest("gamma", shape = 0.2) : dkwtest failed
Execution halted
```

**Comment by JanJecmen** [comment]
Made an experiment on vanilla-r and it randomly fails as well, so probably not a rir-related issue.

To reproduce: (taken from p-r-random-tests.R)
```
superror <- function(rfoo,pfoo,sample.size,...) {
    x <- rfoo(sample.size,...)
    tx <- table(signif(x, 12)) # such that xi will be sort(unique(x))
    xi <- as.numeric(names(tx))
    f <- pfoo(xi,...)
    fhat <- cumsum(tx)/sample.size
    max(abs(fhat-f))
}

pdkwbound <- function(n,t) 2*exp(-2*n*t*t)

qdkwbound <- function(n,p) sqrt(log(p/2)/(-2*n))

dkwtest <- function(stub = "norm", ...,
                    sample.size = 10000, pthreshold = 0.001,
                    print.result = TRUE, print.detail = FALSE,
                    stop.on.failure = TRUE)
{
    rfoo <- eval(as.name(paste("r", stub, sep="")))
    pfoo <- eval(as.name(paste("p", stub, sep="")))
    s <- superror(rfoo, pfoo, sample.size, ...)
    if (print.result || print.detail) {
        printargs <- substitute(list(...))
        printargs[[1]] <- as.name(stub)
        cat(deparse(printargs))
        if (print.detail)
            cat("\nsupremum error = ",signif(s,2),
                " with p-value=",min(1,round(pdkwbound(sample.size,s),4)),"\n")
    }
    rval <- (s < qdkwbound(sample.size,pthreshold))
    if (print.result)
        cat(c(" FAILED\n"," PASSED\n")[rval+1])
    if (stop.on.failure && !rval)
        stop("dkwtest failed")
    rval
}

while (dkwtest("gamma",shape =  0.2)) {}
```
just run and wait

**Comment by o-** [comment]
@JanJecmen so what was the issue with superassign and [[ ?

**Comment by JanJecmen** [comment]
I don't know, didn't find any.

**Pull request merged**
